name: "BackEnd CI/CD"

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/backend.yaml"
      - "infra/**"
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/**"
      - "infra/**"
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: "Run NPM Audit"
        run: |
          npm install
          npm audit --audit-level=high || echo "Audit issues found, review manually."
        
  deployment:
    runs-on: ubuntu-latest
    needs: [security]
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: "Install Dependencies"
        run: npm install

      - name: "Create Deployment Package"
        run: zip -qq -r ../infra/function.zip .

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_ORG_TOKEN }}

      - name: "Terraform Init"
        run: terraform init
        working-directory: infra

      - name: "Terraform Plan"
        run: terraform plan || (echo "Plan unsuccessful, check logs" && exit 1)
        working-directory: infra

      - name: "Terraform Apply"
        run: terraform apply -auto-approve || (echo "Apply unsuccessful, check logs" && exit 1)
        working-directory: infra

      - name: Upload function.zip to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        working-directory: infra
        run: |
          VERSION=$(date +%Y%m%d%H%M%S)
          TAG="backend-release-${VERSION}"
          FILE_PATH="function.zip"
          RELEASE_NAME="Backend"
          gh release create "$TAG" "$FILE_PATH" -t "$RELEASE_NAME" -n "Deployment Package for Backend CI/CD"